import { user } from '../auth-response';

export interface PatientSikkaResponse{
    
    status: string,
    message: string,
    data?: Data[],
    user?: user
}

export interface Data{
    execution_time: string,
    total_count: string,
    limit: string,
    offset: string,
    items: SikkaPatientModel[],
    pagination: Pagination
}

export interface Pagination {
    current: string,
    first: string,
    last: string,
    next: string,
    previous: string
}
export interface SikkaPatientModel{
    address_line1: string,
    address_line2: string,
    alert_note: string,
    appointments: {},
    billing_type: string,
    birthdate: string,
    cell: string,
    city: string,
    country: string,
    created_date: string,
    email: string,
    employer: {},
    employer_id: string,
    fee_no: string,
    first_visit: string,
    firstname: string,
    gender: string,
    guarantor: {},
    guarantor_first_name: string,
    guarantor_id: string,
    guarantor_last_name: string,
    homephone: string,
    href: string,
    hygienist: string,
    image: string,
    integration_ids: string,
    last_visit: string,
    lastname: string,
    medical_note: string,
    middlename: string,
    other_note: string,
    other_phone: string,
    other_referral: string,
    patient_account_id: string,
    patient_codes: string,
    patient_id: string,
    patient_note: string,
    patient_referral: string,
    practice: {},
    practice_id: string,
    preferred_communication_method: string,
    preferred_contact: string,
    preferred_name: string,
    primary_insurance: string,
    primary_insurance_company: {},
    primary_insurance_company_id: string,
    primary_medical_insurance: string,
    primary_medical_insurance_id: string,
    primary_medical_relationship: string,
    primary_medical_subscriber_id: string,
    primary_relationship: string,
    provider: {},
    provider_id: string,
    referred_by_patient_id: string,
    referred_by_provider_id: string,
    referred_out: string,
    salutation: string,
    secondary_insurance: string,
    secondary_insurance_company: {},
    secondary_insurance_company_id: string,
    secondary_medical_insurance: string,
    secondary_medical_insurance_id: string,
    secondary_medical_relationship: string,
    secondary_medical_subscriber_id: string,
    secondary_relationship: string,
    state:string,
    status: string,
    subscriber_id: string,
    thumb_image: string,
    workphone: string,
    zipcode: string,

}